### ISSUE TITLE
Warning in Memory Size

### ISSUE THREAD

**Issue by ghost** [klo2k/nexus3-docker#8] opened 2021-03-26 20:01 UTC
Hello, Thanks for nice image.

I have just tried and found out this warning. Is it possible to correct it? Thanks.

*SYSTEM com.orientechnologies.common.util.OMemory - Configured maximum amount of memory available to the cache (4294967296 bytes) is larger than configured JVM maximum direct memory size (2147483648 bytes). That may cause out of memory errors, please tune the configuration up. Use the -XX:MaxDirectMemorySize JVM option to raise the JVM maximum direct memory size or storage.diskCache.bufferSize OrientDB option to lower memory requirements of the cache.

**Comment by klo2k** [comment] 2021-03-27 09:57
Thanks for letting me know.

Just wondering if you've encountered any actual breakage caused by this?

Else I'll have a look at it when I have time.

PR is always welcome 🙂.

**Comment by ghost** [comment] 2021-03-29 06:23
Thank you for reply. I will write u if i encounter actual breakage.

**Comment by klo2k** [comment] 2024-05-05 04:46
Closing due to old age and no issue reported.

**Closed as completed by klo2k** 2024-05-05 04:46 UTC
Labels: enhancement
